# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: IntelliAPI CI with Maven

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Add Gauge's GPG key
        run: sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
      - name: Add Gauge to the repository list
        run: echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
      - name: Install Gauge
        run: sudo apt-get update && sudo apt-get install gauge
      - name: Install Gauge-Java plugin
        run: gauge install java
      - name: Run pre-requisites tests with Maven
        run: mvn test-compile gauge:execute -DspecsDir="specs" -Dtags="pre_requisites" -Denv="qa"
      - name: Run regression tests with Maven
        run: mvn test-compile gauge:execute -DspecsDir="specs" -Dtags="regression" -Denv="qa" -DinParallel=true
